# This dockerfile builds a container capable of running the SSH CA bot.

FROM alpine:3.11 AS builder

# add dependencies
RUN apk update && apk add --no-cache go curl git musl-dev gcc

# build keybase binary
WORKDIR /go
ENV GOPATH=/go
ENV KEYBASE_VERSION=5.0.0
RUN go get -d github.com/keybase/client/go/keybase
RUN cd src/github.com/keybase/client/go/keybase && git checkout v$KEYBASE_VERSION
RUN go install -tags production github.com/keybase/client/go/keybase

# build kbfsfuse binary
RUN go install -tags production github.com/keybase/client/go/kbfs/kbfsfuse

# build keybaseca
WORKDIR /bot-sshca
COPY . ./
RUN go build -o bin/keybaseca src/cmd/keybaseca/keybaseca.go

FROM alpine:3.11

# copy the keybase binaries from previous build step
COPY --from=builder /go/bin/keybase /usr/local/bin/
COPY --from=builder /go/bin/kbfsfuse /usr/local/bin/
COPY --from=builder /bot-sshca/bin/keybaseca /usr/local/bin/

# bash for entrypoint scripts
# ssh for ssh-keygen used by the bot
# su-exec for stepping down to keybase user
# fuse for kbfs
RUN apk update && apk add --no-cache bash openssh su-exec fuse

# add the keybase user
RUN adduser -s /bin/bash -h /home/keybase -D keybase

# this folder is needed for kbfsfuse
RUN mkdir /keybase && chown keybase:keybase /keybase

USER keybase
WORKDIR /home/keybase

# copy in entrypoint script
COPY ./docker/entrypoint.sh ./

# run container as root, the entrypoint script will step down to keybase user.
USER root
ENTRYPOINT ["/home/keybase/entrypoint.sh"]
